name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore src
    - name: Build
      run: |
        dotnet build src -c release
        dotnet pack src -c release
    - name: nuget auth
      run: dotnet nuget add source --username lolepop --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/lolepop/index.json"
    - name: package
      run: dotnet nuget push "src/IgnoresAccessChecksToGenerator.Tasks/bin/Release/IgnoresAccessChecksToGenerator.0.5.0.nupkg" --api-key ${{ secrets.PAT }} --source "github"
